#!/usr/bin/env python3
import base64
import sys

'''
Currently, a common way to hash passwords using Werkzeug is like this:

    >>> from werkzeug.security import generate_password_hash
    >>> pw_hash = generate_password_hash('rockyou', method='pbkdf2')
    >>> print(pw_hash)
    pbkdf2:sha256:600000$NJmGroHCwx0TCl0z$c10a63e2d93316572ba9d01d674fd720f1df549eb5cf5a35491aec6773d55387
    
I wasn't able to find a hash mode in hashcat that handled this format. However, mode 10900 
"PBKDF2-HMAC-SHA256" is able to handle all the same data, just represented in base064 instead.

This script transforms the hashes generated by generate_password_hash() into hashes that can be processed by
hashcat directly, using mode 10900.

Oct 2024
by 4wayhandshake 🤝🤝🤝🤝
    
'''

def usage():
    print(f'Usage: {sys.argv[0]} input_hash_file output_hash_file')
    sys.exit()

if len(sys.argv) < 3:
    usage()

infile = sys.argv[1]
outfile = sys.argv[2]

with open(infile, 'r') as f_in:
    with open(outfile, 'w') as f_out:
        for in_line in f_in:
            if in_line.startswith('#'):
                continue
            rounds, b64_salt, hex_hash = in_line.rstrip()[len('pbkdf2:sha256:'):].split('$')
            str_salt = base64.b64encode(b64_salt.encode('utf-8')).decode()
            str_hash = base64.b64encode(bytes.fromhex(hex_hash)).decode()
            reassembled_hash = f'sha256:{str(rounds)}:{str_salt}:{str_hash}'
            print(reassembled_hash)
            f_out.write(f'{reassembled_hash}\n')
        print(f'\nUse the following, as a template for cracking the hashes:\nhashcat -m 10900 {outfile} /usr/share/wordlists/rockyou.txt')        
